apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: colosseum

resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - curator-deployment.yaml
  # Do not include secrets.yaml in version control
  # Create secrets manually with kubectl

commonLabels:
  app.kubernetes.io/part-of: colosseum

images:
  - name: ghcr.io/davdunc/colosseum-curator
    newTag: latest
